/// Flutter icons Pokemon
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Pokemon
///      fonts:
///       - asset: fonts/Pokemon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Pokemon {
  Pokemon._();

  static const _kFontFam = 'Pokemon';
  static const String? _kFontPkg = null;

  static const IconData flying = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData grass = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ground = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData normal = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData poison = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData psychic = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rock = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData water = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData electric = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fighting = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fire = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
